border_width = 2
margin = [4, 4]
default_border_color = "#07162D"
floating_border_color = "#8FB4F2"
focused_border_color = "#ccdff4"


col1 = "#054B8F"
col2 = "#1C62A0"
col3 = "#2663A4"
col4 = "#4189CB"
col5 = "#72A9F1"
col6 = "#8FB4F2"
col7 = "#ccdff4"
col8 = "#8e9caa"
col9 = "#054B8F"
col10 = "#1C62A0"
col11 = "#2663A4"
col12 = "#4189CB"
col13 = "#72A9F1"
col14 = "#8FB4F2"
col15 = "#ccdff4"



background = "#07162D"
foreground = "#ccdff4"
